version: "3"
services:
  gerbera:
    image: gerbera/gerbera
    container_name: gerbera
    network_mode: host
    volumes:
      - ./gerberaConfig:/var/run/gerbera/.config/gerbera
      - ./content:/content:ro
    restart: unless-stopped
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./delugeConfig:/config
      - ./content:/downloads
    restart: unless-stopped
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: Media Services
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      #   - ./netdataconfig:/etc/netdata
      #   - ./netdatalib:/var/lib/netdata
      #   - ./netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    restart: unless-stopped