version: "3"
services:
  gerbera:
    image: gerbera/gerbera
    container_name: gerbera
    network_mode: host
    volumes:
      - ./gerberaConfig:/var/run/gerbera/.config/gerbera
      - ./content:/content:ro
    restart: unless-stopped
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./delugeConfig:/config
      - ./content:/downloads
    restart: unless-stopped
  vsftpd:
    image: fauria/vsftpd
    container_name: vsftpd
    ports:
      - 20:20
      - 21:21
      - 21100-21110:21100-21110
    environment:
      - FTP_USER=admin       # Demo only
      - FTP_PASS=12345678x@X # Demo only
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    volumes:
      - ./ftpLog:/var/log/vsftpd
      - ./ftpContent:/home/vsftpd
    restart: unless-stopped
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: Media Services
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    restart: unless-stopped