version: "2.1"
services:
  gerbera:
    image: gerbera/gerbera
    container_name: gerbera
    network_mode: host
    volumes:
      - ./config:/var/run/gerbera/.config/gerbera
      - ./content:/content:ro