version: '2.0'

services:
    app:
        build: 
          context: .
          args:
            VERSION: 1.4.0
        restart: always
        volumes:
            - "/home/truong/nas/pictures:/media/pictures:ro"
            - "/home/truong/nas/videos:/media/videos:ro"
            - "/home/truong/nas/music:/media/music:ro"
            - "${PWD}/config:/home/gerbera/.config/gerbera"
        network_mode: "host"
        restart: always